initialize-release
initializeLicenseCode2
	LicenseCode at: 16r60 put: ' titus'.
	LicenseCode at: 16r61 put: ' virgin'.
	LicenseCode at: 16r67 put: ' ocean'.
	LicenseCode at: 16r69 put: ' electronic arts'.
	LicenseCode at: 16r6E put: ' elite systems'.
	LicenseCode at: 16r6F put: ' electro brain'.
	LicenseCode at: 16r70 put: ' infogrames'.
	LicenseCode at: 16r71 put: ' interplay'.
	LicenseCode at: 16r72 put: ' broderbund'.
	LicenseCode at: 16r73 put: ' sculptered soft'.
	LicenseCode at: 16r75 put: ' the sales curve'.
	LicenseCode at: 16r78 put: ' t*hq'.
	LicenseCode at: 16r79 put: ' accolade'.
	LicenseCode at: 16r7A put: ' triffix entertainment'.
	LicenseCode at: 16r7C put: ' microprose'.
	LicenseCode at: 16r7F put: ' kemco'.
	LicenseCode at: 16r80 put: ' misawa entertainment'.
	LicenseCode at: 16r83 put: ' lozc'.
	LicenseCode at: 16r86 put: ' *tokuma shoten i'.
	LicenseCode at: 16r8B put: ' bullet-proof software'.
	LicenseCode at: 16r8C put: ' vic tokai'.
	LicenseCode at: 16r8E put: ' ape'.
	LicenseCode at: 16r8F put: ' imax'.
	LicenseCode at: 16r91 put: ' chun soft'.
	LicenseCode at: 16r92 put: ' video system'.
	LicenseCode at: 16r93 put: ' tsuburava'.
	LicenseCode at: 16r95 put: ' varie'.
	LicenseCode at: 16r96 put: ' yonezawa/spal'.
	LicenseCode at: 16r97 put: ' kaneko'.
	LicenseCode at: 16r99 put: ' arc'.
	LicenseCode at: 16r9A put: ' nihon bussan'.
	LicenseCode at: 16r9B put: ' tecmo'.
	LicenseCode at: 16r9C put: ' imagineer'.
	LicenseCode at: 16r9D put: ' banpresto'.
	LicenseCode at: 16r9F put: ' nova'.	
	LicenseCode at: 16rA1 put: ' hori electric'.
	LicenseCode at: 16rA2 put: ' bandai'.
	LicenseCode at: 16rA4 put: ' konami'.
	LicenseCode at: 16rA6 put: ' kawada'.
	LicenseCode at: 16rA7 put: ' takara'.
	LicenseCode at: 16rA9 put: ' technos japan'.
	LicenseCode at: 16rAA put: ' broderbund'.
	LicenseCode at: 16rAC put: ' toei animation'.
	LicenseCode at: 16rAD put: ' toho'.
	LicenseCode at: 16rAF put: ' namco'.
	LicenseCode at: 16rB0 put: ' acclaim'.
	LicenseCode at: 16rB1 put: ' ascii or nexoft'.
	LicenseCode at: 16rB2 put: ' bandai'.
	LicenseCode at: 16rB4 put: ' enix'.
	LicenseCode at: 16rB6 put: ' hal'.
	LicenseCode at: 16rB7 put: ' snk'.
	LicenseCode at: 16rB9 put: ' pony canyon'.
	LicenseCode at: 16rBA put: ' *culture brain o'.
	LicenseCode at: 16rBB put: ' sunsoft'.
	LicenseCode at: 16rBD put: ' sony imagesoft'.
	LicenseCode at: 16rBF put: ' sammy'.
	LicenseCode at: 16rC0 put: ' taito'.
	LicenseCode at: 16rC2 put: ' kemco'.
	LicenseCode at: 16rC3 put: ' squaresoft'.
	LicenseCode at: 16rC4 put: ' *tokuma shoten i'.
	LicenseCode at: 16rC5 put: ' data east'.
	LicenseCode at: 16rC6 put: ' tonkin house'.
	LicenseCode at: 16rC8 put: ' koei'.
	LicenseCode at: 16rC9 put: ' ufl'.
	LicenseCode at: 16rCA put: ' ultra'.
	LicenseCode at: 16rCB put: ' vap'.
	LicenseCode at: 16rCC put: ' use'.
	LicenseCode at: 16rCD put: ' meldac'.
	LicenseCode at: 16rCE put: ' *pony canyon or'.
	LicenseCode at: 16rCF put: ' angel'.
	LicenseCode at: 16rD0 put: ' taito'.
	LicenseCode at: 16rD1 put: ' sofel'.
	LicenseCode at: 16rD2 put: ' quest'.
	LicenseCode at: 16rD3 put: ' sigma enterprises'.
	LicenseCode at: 16rD4 put: ' ask kodansha'.
	LicenseCode at: 16rD6 put: ' naxat soft'.
	LicenseCode at: 16rD7 put: ' copya systems'.
	LicenseCode at: 16rD9 put: ' banpresto'.
	LicenseCode at: 16rDA put: ' tomy'.
	LicenseCode at: 16rDB put: ' ljn'.
	LicenseCode at: 16rDD put: ' ncs'.
	LicenseCode at: 16rDE put: ' human'.
	LicenseCode at: 16rDF put: ' altron'.
	LicenseCode at: 16rE0 put: ' jaleco'.
	LicenseCode at: 16rE1 put: ' towachiki'.
	LicenseCode at: 16rE2 put: ' uutaka'.
	LicenseCode at: 16rE3 put: ' varie'.
	LicenseCode at: 16rE5 put: ' epoch'.
	LicenseCode at: 16rE7 put: ' athena'.
	LicenseCode at: 16rE8 put: ' asmik'.
	LicenseCode at: 16rE9 put: ' natsume'.
	LicenseCode at: 16rEA put: ' king records'.
	LicenseCode at: 16rEB put: ' atlus'.
	LicenseCode at: 16rEC put: ' epic/sony records'.
	LicenseCode at: 16rEE put: ' igs'.
	LicenseCode at: 16rF0 put: ' a wave'.
	LicenseCode at: 16rF3 put: ' extreme entertainment'.
	LicenseCode at: 16rFF put: ' ljn'