initialize-release
initializeLicenseCode
	"LicenseCode at: 16r00 put: ' none'. "
	
	LicenseCode := Array new: 16rff withAll: 'UNKNOWN' .
	LicenseCode at: 16r01 put: ' nintendo'.
	LicenseCode at: 16r08 put: ' capcom'.
	LicenseCode at: 16r09 put: ' hot-b'.
	LicenseCode at: 16r0A put: ' jaleco'.
	LicenseCode at: 16r0B put: ' coconuts'.
	LicenseCode at: 16r0C put: ' elite systems'.
	LicenseCode at: 16r13 put: ' electronic arts'.
	LicenseCode at: 16r18 put: ' hudsonsoft'.
	LicenseCode at: 16r19 put: ' itc entertainment'.
	LicenseCode at: 16r1A put: ' yanoman'.
	LicenseCode at: 16r1D put: ' clary'.
	LicenseCode at: 16r1F put: ' virgin'.
	LicenseCode at: 16r24 put: ' pcm complete'.
	LicenseCode at: 16r25 put: ' san-x'.
	LicenseCode at: 16r28 put: ' kotobuki systems'.	
	LicenseCode at: 16r29 put: ' seta'.
	LicenseCode at: 16r30 put: ' infogrames'.
	LicenseCode at: 16r31 put: ' nintendo'.
	LicenseCode at: 16r32 put: ' bandai'.
	LicenseCode at: 16r33 put: 'GBC - see above'.
	LicenseCode at: 16r34 put: ' konami'.
	LicenseCode at: 16r35 put: ' hector'.
	LicenseCode at: 16r38 put: ' capcom'.
	LicenseCode at: 16r39 put: ' banpresto'.
	LicenseCode at: 16r3C put: ' *entertainment i'.
	LicenseCode at: 16r3E put: ' gremlin'.
	LicenseCode at: 16r41 put: ' ubi soft'.
	LicenseCode at: 16r42 put: ' atlus'.
	LicenseCode at: 16r44 put: ' malibu'.
	LicenseCode at: 16r46 put: ' angel'.
	LicenseCode at: 16r47 put: ' spectrum holoby'.
	LicenseCode at: 16r49 put: ' irem'.
	LicenseCode at: 16r4A put: ' virgin'.
	LicenseCode at: 16r4D put: ' malibu'.
	LicenseCode at: 16r4F put: ' u.s. gold'.
	LicenseCode at: 16r50 put: ' absolute'.
	LicenseCode at: 16r51 put: ' acclaim'.
	LicenseCode at: 16r52 put: ' activision'.
	LicenseCode at: 16r53 put: ' american sammy'.
	LicenseCode at: 16r54 put: ' gametek'.
	LicenseCode at: 16r55 put: ' park place'.
	LicenseCode at: 16r56 put: ' ljn'.
	LicenseCode at: 16r57 put: ' matchbox'.
	LicenseCode at: 16r59 put: ' milton bradley'.
	LicenseCode at: 16r5A put: ' mindscape'.
	LicenseCode at: 16r5B put: ' romstar'.
	LicenseCode at: 16r5C put: ' naxat soft'.
	LicenseCode at: 16r5D put: ' tradewest'.