as yet unclassified
createOpCodesInto: anArray withProcessor: aProcessor
	anArray at: 212 put: ( self newInstruction: 212 forProcessor: aProcessor withArg: { }).
	anArray at: 220 put: ( self newInstruction: 220 forProcessor: aProcessor withArg: { }).
	anArray at: 222 put: ( self newInstruction: 222 forProcessor: aProcessor withArg: { }).
	anArray at: 228 put: ( self newInstruction: 228 forProcessor: aProcessor withArg: { }).
	anArray at: 229 put: ( self newInstruction: 229 forProcessor: aProcessor withArg: { }).
	anArray at: 236 put: ( self newInstruction: 236 forProcessor: aProcessor withArg: { }).
	anArray at: 237 put: ( self newInstruction: 237 forProcessor: aProcessor withArg: { }).
	anArray at: 238 put: ( self newInstruction: 238 forProcessor: aProcessor withArg: { }).
	anArray at: 245 put: ( self newInstruction: 245 forProcessor: aProcessor withArg: { }).
	anArray at: 253 put: ( self newInstruction: 253 forProcessor: aProcessor withArg: { }).
	anArray at: 254 put: ( self newInstruction: 254 forProcessor: aProcessor withArg: { }).
	
	
	