as yet unclassified
createExtendedOpCodesInto: anArray withProcessor: aProgress
	"GBSET0B"
	anArray at: 193 put: ( self newInstruction: 193 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET0C"
	anArray at: 194 put: ( self newInstruction: 194 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET0D"	
	anArray at: 195 put: ( self newInstruction: 195 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET0E"	
	anArray at: 196 put: ( self newInstruction: 196 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET0H"	
	anArray at: 197 put: ( self newInstruction: 197 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET0L"	
	anArray at: 198 put: ( self newInstruction: 198 forProcessor: aProgress withArg: { } tick: 8).


	"GBSET0A"
	anArray at: 200 put: ( self newInstruction: 200 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET1B"
	anArray at: 201 put: ( self newInstruction: 201 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET1C"	
	anArray at: 202 put: ( self newInstruction: 202 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET1D"	
	anArray at: 203 put: ( self newInstruction: 203 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET1E"	
	anArray at: 204 put: ( self newInstruction: 204 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET1H"	
	anArray at: 205 put: ( self newInstruction: 205 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET1L"	
	anArray at: 206 put: ( self newInstruction: 206 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET1A"	
	anArray at: 208 put: ( self newInstruction: 208 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET2B"	
	anArray at: 209 put: ( self newInstruction: 209 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET2C"	
	anArray at: 210 put: ( self newInstruction: 210 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET2D"	
	anArray at: 211 put: ( self newInstruction: 211 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET2E"	
	anArray at: 212 put: ( self newInstruction: 212 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET2H"	
	anArray at: 213 put: ( self newInstruction: 213 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET2L"	
	anArray at: 214 put: ( self newInstruction: 214 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET2A"	
	anArray at: 216 put: ( self newInstruction: 216 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET3B"
	anArray at: 217 put: ( self newInstruction: 217 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET3C"	
	anArray at: 218 put: ( self newInstruction: 218 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET3D"	
	anArray at: 219 put: ( self newInstruction: 219 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET3E"	
	anArray at: 220 put: ( self newInstruction: 220 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET3H"	
	anArray at: 221 put: ( self newInstruction: 221 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET3L"	
	anArray at: 222 put: ( self newInstruction: 222 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET3A"	
	anArray at: 224 put: ( self newInstruction: 224 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET4B"	
	anArray at: 225 put: ( self newInstruction: 225 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET4C"	
	anArray at: 226 put: ( self newInstruction: 226 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET4D"	
	anArray at: 227 put: ( self newInstruction: 227 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET4E"	
	anArray at: 228 put: ( self newInstruction: 228 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET4H"	
	anArray at: 229 put: ( self newInstruction: 229 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET4L"	
	anArray at: 230 put: ( self newInstruction: 230 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET4A"	
	anArray at: 232 put: ( self newInstruction: 232 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET5B"	
	anArray at: 233 put: ( self newInstruction: 233 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET5C"	
	anArray at: 234 put: ( self newInstruction: 234 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET5D"	
	anArray at: 235 put: ( self newInstruction: 235 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET5E"	
	anArray at: 236 put: ( self newInstruction: 236 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET5H"	
	anArray at: 237 put: ( self newInstruction: 237 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET5L"	
	anArray at: 238 put: ( self newInstruction: 238 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET5A"	
	anArray at: 240 put: ( self newInstruction: 240 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET6B"	
	anArray at: 241 put: ( self newInstruction: 241 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET6C"	
	anArray at: 242 put: ( self newInstruction: 242 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET6D"	
	anArray at: 243 put: ( self newInstruction: 243 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET6E"	
	anArray at: 244 put: ( self newInstruction: 244 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET6H"	
	anArray at: 245 put: ( self newInstruction: 245 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET6L"	
	anArray at: 246 put: ( self newInstruction: 246 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET6A"	
	anArray at: 248 put: ( self newInstruction: 248 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET7B"	
	anArray at: 249 put: ( self newInstruction: 249 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET7C"	
	anArray at: 250 put: ( self newInstruction: 250 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET7D"	
	anArray at: 251 put: ( self newInstruction: 251 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET7E"	
	anArray at: 252 put: ( self newInstruction: 252 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET7H"	
	anArray at: 253 put: ( self newInstruction: 253 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET7L"	
	anArray at: 254 put: ( self newInstruction: 254 forProcessor: aProgress withArg: { } tick: 8).

	"GBSET7A"	
	anArray at: 256 put: ( self newInstruction: 256 forProcessor: aProgress withArg: { } tick: 8).

	