as yet unclassified
createExtendedOpCodesInto: anArray withProcessor: aPro
	"GBRES0B"
	anArray at: 129 put: ( self newInstruction: 129 forProcessor: aPro withArg: {0. aPro b } tick: 8).
	
	"GBRES0C"
	anArray at: 130 put: ( self newInstruction: 130 forProcessor: aPro withArg: {0. aPro c } tick: 8).

	"GBRES0D"	
	anArray at: 131 put: ( self newInstruction: 131 forProcessor: aPro withArg: {0. aPro d } tick: 8).

	"GBRES0E"	
	anArray at: 132 put: ( self newInstruction: 132 forProcessor: aPro withArg: {0. aPro e } tick: 8).

	"GBRES0H"	
	anArray at: 133 put: ( self newInstruction: 133 forProcessor: aPro withArg: {0. aPro h } tick: 8).

	"GBRES0L"	
	anArray at: 134 put: ( self newInstruction: 134 forProcessor: aPro withArg: {0. aPro l } tick: 8).

	"GBRES0A"	
	anArray at: 136 put: ( self newInstruction: 136 forProcessor: aPro withArg: {0. aPro a } tick: 8).

	"GBRES1B"	
	anArray at: 137 put: ( self newInstruction: 137 forProcessor: aPro withArg: {1. aPro b} tick: 8).

	"GBRES1C"	
	anArray at: 138 put: ( self newInstruction: 138 forProcessor: aPro withArg: {1. aPro c} tick: 8).

	"GBRES1D"	
	anArray at: 139 put: ( self newInstruction: 139 forProcessor: aPro withArg: {1. aPro d} tick: 8).

	"GBRES1E"	
	anArray at: 140 put: ( self newInstruction: 140 forProcessor: aPro withArg: {1. aPro e} tick: 8).

	"GBRES1H"	
	anArray at: 141 put: ( self newInstruction: 141 forProcessor: aPro withArg: {1. aPro h} tick: 8).

	"GBRES1L"	
	anArray at: 142 put: ( self newInstruction: 142 forProcessor: aPro withArg: {1. aPro l} tick: 8).

	"GBRES1A"	
	anArray at: 144 put: ( self newInstruction: 144 forProcessor: aPro withArg: {2. aPro a } tick: 8).

	"GBRES2B"	
	anArray at: 145 put: ( self newInstruction: 145 forProcessor: aPro withArg: {2. aPro b } tick: 8).

	"GBRES2C"	
	anArray at: 146 put: ( self newInstruction: 146 forProcessor: aPro withArg: {2. aPro c } tick: 8).

	"GBRES2D"	
	anArray at: 147 put: ( self newInstruction: 147 forProcessor: aPro withArg: {2. aPro d } tick: 8).

	"GBRES2E"	
	anArray at: 148 put: ( self newInstruction: 148 forProcessor: aPro withArg: {2. aPro e } tick: 8).

	"GBRES2H"	
	anArray at: 149 put: ( self newInstruction: 149 forProcessor: aPro withArg: {2. aPro h } tick: 8).

	"GBRES2L"	
	anArray at: 150 put: ( self newInstruction: 150 forProcessor: aPro withArg: {2. aPro l } tick: 8).

	"GBRES2A"	
	anArray at: 152 put: ( self newInstruction: 152 forProcessor: aPro withArg: {3. aPro a } tick: 8).

	"GBRES3B"	
	anArray at: 153 put: ( self newInstruction: 153 forProcessor: aPro withArg: {3. aPro b } tick: 8).

	"GBRES3C"	
	anArray at: 154 put: ( self newInstruction: 154 forProcessor: aPro withArg: {3. aPro c } tick: 8).

	"GBRES3D"	
	anArray at: 155 put: ( self newInstruction: 155 forProcessor: aPro withArg: {3. aPro d } tick: 8).

	"GBRES3E"	
	anArray at: 156 put: ( self newInstruction: 156 forProcessor: aPro withArg: {3. aPro e } tick: 8).

	"GBRES3H"	
	anArray at: 157 put: ( self newInstruction: 157 forProcessor: aPro withArg: {3. aPro h } tick: 8).

	"GBRES3L"	
	anArray at: 158 put: ( self newInstruction: 158 forProcessor: aPro withArg: {3. aPro l } tick: 8).

	"GBRES3A"	
	anArray at: 160 put: ( self newInstruction: 160 forProcessor: aPro withArg: {3. aPro a} tick: 8).

	"GBRES4B"	
	anArray at: 161 put: ( self newInstruction: 161 forProcessor: aPro withArg: {4. aPro b } tick: 8).

	"GBRES4C"	
	anArray at: 162 put: ( self newInstruction: 162 forProcessor: aPro withArg: {4. aPro c } tick: 8).

	"GBRES4D"	
	anArray at: 163 put: ( self newInstruction: 163 forProcessor: aPro withArg: {4. aPro d } tick: 8).

	"GBRES4E"	
	anArray at: 164 put: ( self newInstruction: 164 forProcessor: aPro withArg: {4. aPro e } tick: 8).

	"GBRES4H"	
	anArray at: 165 put: ( self newInstruction: 165 forProcessor: aPro withArg: {4. aPro h } tick: 8).

	"GBRES4L"	
	anArray at: 166 put: ( self newInstruction: 166 forProcessor: aPro withArg: {4. aPro l } tick: 8).

	"GBRES4A"	
	anArray at: 168 put: ( self newInstruction: 168 forProcessor: aPro withArg: { 4. aPro a} tick: 8).

	"GBRES5B"	
	anArray at: 169 put: ( self newInstruction: 169 forProcessor: aPro withArg: {5. aPro b } tick: 8).

	"GBRES5C"	
	anArray at: 170 put: ( self newInstruction: 170 forProcessor: aPro withArg: {5. aPro c } tick: 8).

	"GBRES5D"	
	anArray at: 171 put: ( self newInstruction: 171 forProcessor: aPro withArg: { 5. aPro d} tick: 8).

	"GBRES5E"	
	anArray at: 172 put: ( self newInstruction: 172 forProcessor: aPro withArg: {5. aPro e } tick: 8).

	"GBRES5H"	
	anArray at: 173 put: ( self newInstruction: 173 forProcessor: aPro withArg: {5. aPro h } tick: 8).

	"GBRES5L"	
	anArray at: 174 put: ( self newInstruction: 174 forProcessor: aPro withArg: {5. aPro l } tick: 8).

	"GBRES5A"	
	anArray at: 176 put: ( self newInstruction: 176 forProcessor: aPro withArg: {5. aPro a } tick: 8).

	"GBRES6B"	
	anArray at: 177 put: ( self newInstruction: 177 forProcessor: aPro withArg: { 6. aPro b} tick: 8).

	"GBRES6C"	
	anArray at: 178 put: ( self newInstruction: 178 forProcessor: aPro withArg: {6. aPro c } tick: 8).

	"GBRES6D"	
	anArray at: 179 put: ( self newInstruction: 179 forProcessor: aPro withArg: {6. aPro d } tick: 8).

	"GBRES6E"	
	anArray at: 180 put: ( self newInstruction: 180 forProcessor: aPro withArg: {6. aPro e } tick: 8).

	"GBRES6H"	
	anArray at: 181 put: ( self newInstruction: 181 forProcessor: aPro withArg: {6. aPro h } tick: 8).

	"GBRES6L"	
	anArray at: 182 put: ( self newInstruction: 182 forProcessor: aPro withArg: {6. aPro l } tick: 8).

	"GBRES6A"	
	anArray at: 184 put: ( self newInstruction: 184 forProcessor: aPro withArg: {6. aPro a } tick: 8).

	"GBRES7B"	
	anArray at: 185 put: ( self newInstruction: 185 forProcessor: aPro withArg: {7. aPro b} tick: 8).

	"GBRES7C"	
	anArray at: 186 put: ( self newInstruction: 186 forProcessor: aPro withArg: {7. aPro c } tick: 8).

	"GBRES7D"	
	anArray at: 187 put: ( self newInstruction: 187 forProcessor: aPro withArg: {7. aPro d } tick: 8).

	"GBRES7E"	
	anArray at: 188 put: ( self newInstruction: 188 forProcessor: aPro withArg: {7. aPro e } tick: 8).

	"GBRES7H"	
	anArray at: 189 put: ( self newInstruction: 189 forProcessor: aPro withArg: { 7. aPro h} tick: 8).

	"GBRES7L"	
	anArray at: 190 put: ( self newInstruction: 190 forProcessor: aPro withArg: {7. aPro l } tick: 8).

	"GBRES7A"	
	anArray at: 192 put: ( self newInstruction: 192 forProcessor: aPro withArg: {7. aPro a } tick: 8).

	