initialization
initializeShortcut	
	"value keycode + 1 ===> a = 0 + 1"
	shortcutTableUp at: 1 put: #aUp.
	shortcutTableDown at: 1 put: #aDown.	
	shortcutTableUp at: 2 put: #bUp.
	shortcutTableDown at: 2 put: #bDown.	
	shortcutTableUp at: 50 put: #selectUp.
	shortcutTableDown at: 50 put: #selectDown.	
	shortcutTableUp at:  37 put: #startUp.
	shortcutTableDown at:  37 put: #startDown.	

	
	
	shortcutTableUp at: 127 put: #topUp.
	shortcutTableDown at: 127 put: #topDown.	
	shortcutTableUp at: 126 put: #downUp.
	shortcutTableDown at: 126 put: #downDown.	
	shortcutTableUp at: 124 put: #leftUp.
	shortcutTableDown at: 124 put: #leftDown.	
	shortcutTableUp at: 125 put: #rightUp.
	shortcutTableDown at: 125 put: #rightDown.	


 

