as yet unclassified
createExtendedOpCodesInto: anArray withProcessor: aProcessor
	"GBSRLr_b"
	anArray at: 57 put: ( self newInstruction: 57 forProcessor: aProcessor withArg: {aProcessor b } tick: 8).

	"GBSRLr_c"
	anArray at: 58 put: ( self newInstruction: 58 forProcessor: aProcessor withArg: {aProcessor c } tick: 8).

	"GBSRLr_d"
	anArray at: 59 put: ( self newInstruction: 59 forProcessor: aProcessor withArg: {aProcessor d } tick: 8).

	"GBSRLr_e"
	anArray at: 60 put: ( self newInstruction: 60 forProcessor: aProcessor withArg: {aProcessor e } tick: 8).

	"GBSRLr_h"
	anArray at: 61 put: ( self newInstruction: 61 forProcessor: aProcessor withArg: {aProcessor h } tick: 8).

	"GBSRLr_l"
	anArray at: 62 put: ( self newInstruction: 62 forProcessor: aProcessor withArg: {aProcessor l } tick: 8).

	"GBSRLr_a"
	anArray at: 64 put: ( self newInstruction: 64 forProcessor: aProcessor withArg: {aProcessor a } tick: 8).

	