as yet unclassified
createExtendedOpCodesInto: anArray withProcessor: aProcessor
	"GBBIT0b"
	anArray at: 65 put: ( self newInstruction: 65 forProcessor: aProcessor withArg: {0. aProcessor b} tick: 8).

	"GBBIT0c"
	anArray at: 66 put: ( self newInstruction: 66 forProcessor: aProcessor withArg: {0. aProcessor c } tick: 8).

	"GBBIT0d"
	anArray at: 67 put: ( self newInstruction: 67 forProcessor: aProcessor withArg: {0. aProcessor d } tick: 8).

	"GBBIT0e"
	anArray at: 68 put: ( self newInstruction: 68 forProcessor: aProcessor withArg: {0. aProcessor e } tick: 8).

	"GBBIT0h"
	anArray at: 69 put: ( self newInstruction: 69 forProcessor: aProcessor withArg: {0. aProcessor h } tick: 8).

	"GBBIT0l"
	anArray at: 70 put: ( self newInstruction: 70 forProcessor: aProcessor withArg: {0. aProcessor l } tick: 8).

	"GBBIT0a"
	anArray at: 72 put: ( self newInstruction: 72 forProcessor: aProcessor withArg: {0. aProcessor a } tick: 8).

	"GBBIT1b"
	anArray at: 73 put: ( self newInstruction: 73 forProcessor: aProcessor withArg: {1. aProcessor  b} tick: 8).

	"GBBIT1c"
	anArray at: 74 put: ( self newInstruction: 74 forProcessor: aProcessor withArg: {1. aProcessor  c } tick: 8).

	"GBBIT1d"
	anArray at: 75 put: ( self newInstruction: 75 forProcessor: aProcessor withArg: {1. aProcessor  d } tick: 8).

	"GBBIT1e"
	anArray at: 76 put: ( self newInstruction: 76 forProcessor: aProcessor withArg: {1. aProcessor  e } tick: 8).

	"GBBIT1h"
	anArray at: 77 put: ( self newInstruction: 77 forProcessor: aProcessor withArg: {1. aProcessor  h } tick: 8).

	"GBBIT1l"
	anArray at: 78 put: ( self newInstruction: 78 forProcessor: aProcessor withArg: {1. aProcessor  l } tick: 8).

	"GBBIT1a"
	anArray at: 80 put: ( self newInstruction: 80 forProcessor: aProcessor withArg: {1. aProcessor  a } tick: 8).

	"GBBIT2b"
	anArray at: 81 put: ( self newInstruction: 81 forProcessor: aProcessor withArg: {2. aProcessor  b } tick: 8).

	"GBBIT2c"
	anArray at: 82 put: ( self newInstruction: 82 forProcessor: aProcessor withArg: {2. aProcessor  c } tick: 8).

	"GBBIT2d"
	anArray at: 83 put: ( self newInstruction: 83 forProcessor: aProcessor withArg: {2. aProcessor  d } tick: 8).

	"GBBIT2e"
	anArray at: 84 put: ( self newInstruction: 84 forProcessor: aProcessor withArg: {2. aProcessor  e } tick: 8).

	"GBBIT2h"
	anArray at: 85 put: ( self newInstruction: 85 forProcessor: aProcessor withArg: {2. aProcessor  h } tick: 8).

	"GBBIT2l"
	anArray at: 86 put: ( self newInstruction: 86 forProcessor: aProcessor withArg: {2. aProcessor  l } tick: 8).

	"GBBIT2a"
	anArray at: 88 put: ( self newInstruction: 88 forProcessor: aProcessor withArg: {2. aProcessor  a } tick: 8).

	"GBBIT3b"
	anArray at: 89 put: ( self newInstruction: 89 forProcessor: aProcessor withArg: {3. aProcessor  b } tick: 8).

	"GBBIT3c"
	anArray at: 90 put: ( self newInstruction: 90 forProcessor: aProcessor withArg: {3. aProcessor c } tick: 8).

	"GBBIT3d"
	anArray at: 91 put: ( self newInstruction: 91 forProcessor: aProcessor withArg: {3. aProcessor d } tick: 8).

	"GBBIT3e"
	anArray at: 92 put: ( self newInstruction: 92 forProcessor: aProcessor withArg: {3. aProcessor e } tick: 8).

	"GBBIT3h"
	anArray at: 93 put: ( self newInstruction: 93 forProcessor: aProcessor withArg: {3. aProcessor h } tick: 8).

	"GBBIT3l"
	anArray at: 94 put: ( self newInstruction: 94 forProcessor: aProcessor withArg: {3. aProcessor l } tick: 8).

	"GBBIT3a"
	anArray at: 96 put: ( self newInstruction: 96 forProcessor: aProcessor withArg: {3. aProcessor a } tick: 8).

	"GBBIT4b"
	anArray at: 97 put: ( self newInstruction: 97 forProcessor: aProcessor withArg: {4. aProcessor b } tick: 8).

	"GBBIT4c"
	anArray at: 98 put: ( self newInstruction: 98 forProcessor: aProcessor withArg: {4. aProcessor c } tick: 8).

	"GBBIT4d"
	anArray at: 99 put: ( self newInstruction: 99 forProcessor: aProcessor withArg: {4. aProcessor d } tick: 8).

	"GBBIT4e"
	anArray at: 100 put: ( self newInstruction: 100 forProcessor: aProcessor withArg: {4. aProcessor e } tick: 8).

	"GBBIT4h"
	anArray at: 101 put: ( self newInstruction: 101 forProcessor: aProcessor withArg: {4. aProcessor h } tick: 8).

	"GBBIT4l"
	anArray at: 102 put: ( self newInstruction: 102 forProcessor: aProcessor withArg: {4. aProcessor l } tick: 8).

	"GBBIT4a"
	anArray at: 104 put: ( self newInstruction: 104 forProcessor: aProcessor withArg: {4. aProcessor a } tick: 8).

	"GBBIT5b"
	anArray at: 105 put: ( self newInstruction: 105 forProcessor: aProcessor withArg: {5. aProcessor b } tick: 8).

	"GBBIT5c"
	anArray at: 106 put: ( self newInstruction: 106 forProcessor: aProcessor withArg: {5. aProcessor c } tick: 8).

	"GBBIT5d"
	anArray at: 107 put: ( self newInstruction: 107 forProcessor: aProcessor withArg: {5. aProcessor d } tick: 8).

	"GBBIT5e"
	anArray at: 108 put: ( self newInstruction: 108 forProcessor: aProcessor withArg: {5. aProcessor e } tick: 8).

	"GBBIT5h"
	anArray at: 109 put: ( self newInstruction: 109 forProcessor: aProcessor withArg: {5. aProcessor h } tick: 8).

	"GBBIT5l"
	anArray at: 110 put: ( self newInstruction: 110 forProcessor: aProcessor withArg: {5. aProcessor l } tick: 8).

	"GBBIT5a"
	anArray at: 112 put: ( self newInstruction: 112 forProcessor: aProcessor withArg: {5. aProcessor a } tick: 8).

	"GBBIT6b"
	anArray at: 113 put: ( self newInstruction: 113 forProcessor: aProcessor withArg: {6. aProcessor b } tick: 8).

	"GBBIT6c"
	anArray at: 114 put: ( self newInstruction: 114 forProcessor: aProcessor withArg: {6. aProcessor c } tick: 8).

	"GBBIT6d"
	anArray at: 115 put: ( self newInstruction: 115 forProcessor: aProcessor withArg: {6. aProcessor d } tick: 8).

	"GBBIT6e"
	anArray at: 116 put: ( self newInstruction: 116 forProcessor: aProcessor withArg: {6. aProcessor e } tick: 8).

	"GBBIT6h"
	anArray at: 117 put: ( self newInstruction: 117 forProcessor: aProcessor withArg: {6. aProcessor h } tick: 8).

	"GBBIT6l"
	anArray at: 118 put: ( self newInstruction: 118 forProcessor: aProcessor withArg: {6. aProcessor l } tick: 8).

	"GBBIT6a"
	anArray at: 120 put: ( self newInstruction: 120 forProcessor: aProcessor withArg: {6. aProcessor a } tick: 8).

	"GBBIT7b"
	anArray at: 121 put: ( self newInstruction: 121 forProcessor: aProcessor withArg: {7. aProcessor b } tick: 8).

	"GBBIT7c"
	anArray at: 122 put: ( self newInstruction: 122 forProcessor: aProcessor withArg: {7. aProcessor c } tick: 8).

	"GBBIT7d"
	anArray at: 123 put: ( self newInstruction: 123 forProcessor: aProcessor withArg: {7. aProcessor d } tick: 8).

	"GBBIT7e"
	anArray at: 124 put: ( self newInstruction: 124 forProcessor: aProcessor withArg: {7. aProcessor e} tick: 8).

	"GBBIT7h"
	anArray at: 125 put: ( self newInstruction: 125 forProcessor: aProcessor withArg: {7. aProcessor h } tick: 8).

	"GBBIT7l"
	anArray at: 126 put: ( self newInstruction: 126 forProcessor: aProcessor withArg: {7. aProcessor l } tick: 8).

	"GBBIT7a"
	anArray at: 128 put: ( self newInstruction: 128 forProcessor: aProcessor withArg: {7. aProcessor a } tick: 8).

	